apiVersion: v1
kind: Secret
metadata:
  name: pgsql-backup-secret
type: Opaque
stringData:
    PG_HOST: "postgresql"
    PG_PASSWORD: "admin"
    PG_USER: "postgres"
    PG_DATABASE: "pelican_db"
    AWS_ACCESS_KEY_ID: "admin"
    AWS_SECRET_ACCESS_KEY: "rootPassword"
    AWS_BUCKET_NAME: "pelican-local-env"
    AWS_HOST: "http://minio-s3:9000"
