name: CronJob E2E Test

on:
  push:
    branches:
      - test/e2e-test

jobs:
  e2e_test:
    name: Run E2E tests
    needs: push_to_registry
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest

      - name: Configure AWS credentials for testing
        run: |
          mkdir -p ~/.aws
          echo "[default]\naws_access_key_id = test\naws_secret_access_key = test" > ~/.aws/credentials

      - name: Run local S3 server (minio)
        run: |
          docker run -d -p 9000:9000 -p 9090:9090 --name minio \
            -e "MINIO_ROOT_USER=test" \
            -e "MINIO_ROOT_PASSWORD=testtest" \
            minio/minio server /data --console-address ":9090"

      - name: Wait for services to be ready
        run: |
          docker exec minio mc alias set local http://localhost:9000 test testtest
          docker exec minio mc mb local/test-bucket
          sleep 10

      - name: Run e2e test
        env:
          DB_BACKUPS_FILENAME_PREFIX: test-backup
          DATABASE_HOST: localhost
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: testdb
          DESTINATION_DB_AWS_ACCESS_KEY_ID: test
          DESTINATION_DB_AWS_SECRET_ACCESS_KEY: testtest
          DESTINATION_DB_AWS_BUCKET_NAME: test-bucket
          DESTINATION_DB_AWS_ENDPOINT: http://localhost:9000
        run: |
          python pgsql-dump.py
          python -m pytest -v e2e_test.py